### ISSUE TITLE
form with no submissions shows time span since unix epoch

### ISSUE THREAD

**Issue by cmpscabral** [snoopForms/snoopHub#11]
![Screenshot 2022-08-01 at 14 43 55](https://user-images.githubusercontent.com/197300/182162071-b2c85d56-05dc-40cc-bfe0-5e576941fbaa.png)

**Comment by matthiasnannt** [comment]
@cmpscabral thanks for the bug report. going to fix that 😊

**Comment by matthiasnannt** [comment]
Problem got fixed with commit https://github.com/snoopForms/snoopHub/commit/75d7700d255f512d93a8e75bab759f81efb1099d
