### ISSUE TITLE
client-side exception on analytics page

### ISSUE THREAD

**Issue by wyzlle** [snoopForms/snoopHub#14]
uBlock origin blocks this URL (`https://app.snoopforms.com/_next/data/ZObSlVPulsX2PbV4kEorp/forms/<form-id>/results/analytics.json?id=<form-id>`) and that causes a client-side exception on `https://app.snoopforms.com/forms/<form-id>/results/analytics`. 
![image](https://user-images.githubusercontent.com/101371689/183083783-ee8a5f74-2fa0-4405-9cdd-cdee4bc32d6b.png)

Renaming `analytics.json` to `insights.json` or something else should fix this

**Comment by matthiasnannt** [comment]
@wyzlle thanks for reporting. will fix that 😊
