### ISSUE TITLE
[Bug Report] It breaks down if I alter a form which has submissions before

### ISSUE THREAD

**Issue by KyLoc20** [snoopForms/snoopHub#55]
### Step1 Build a nocode form with 2 questions
![1](https://user-images.githubusercontent.com/75946573/184101400-a1b16ff0-f1b3-40e6-8328-c9ade48a3221.png)

### Step2 Make a submission and check the Summary Tab, it works well
![2](https://user-images.githubusercontent.com/75946573/184101603-d35c612a-09d3-4258-8bb9-94b32bf1ec9f.png)

### Step3 Alter the form by deleting the question Q1
![3](https://user-images.githubusercontent.com/75946573/184101735-82f0f6a4-d961-480a-9bed-9abed48ece8d.png)

### Step4 Before make a new submission, go to check the Summary Tab, it still works well
![4](https://user-images.githubusercontent.com/75946573/184101914-5dcf4819-d96b-424e-ba67-0d6ac64552e8.png)

### Step5 Make a new submission, go to check the Summary Tab, it breaks down
![5](https://user-images.githubusercontent.com/75946573/184102050-d1189a42-c793-47e2-9716-1d57852b454c.png)

**Comment by matthiasnannt** [comment]
thanks @KyLoc20 for the detailed bugreport 😊💪
issue is fixed now 😊
